# Sandbox DNA-C Params
# https://sandboxdnac.cisco.com/

DnaCenter:
  Hostname: sandboxdnac.cisco.com
  Port: 443
  Username: devnetuser
  Password: Cisco123!

IntentApiV1NetworkDevice:
  Hosts: asr1001-x,cat_9k_1.abc.inc,cat_9k_2,cs3850.abc.inc

IntentApiV1NetworkDeviceCount:
  Version: '1.0'